sudo: required
services:
  - docker/compose:1.23.1

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script:
        - docker-compose run --rm web python manage.py test lists

    - name: "Func Tests"
      script:
        - |
          docker pull selenoid/chrome:72.0
          docker-compose --file docker-compose.test.yml build
          docker network create --attachable=true --driver=bridge selenoid-test
          docker network ls
          docker-compose --file docker-compose.test.yml run --rm web

    - stage: "Deploy"
      name: "Deploy Prod"
      script:
        - >
          echo $HEROKU_API_KEY # Travis not reveals the secret keys

          # login
          echo "HEROKU_API_KEY | docker login --username=$HEROKU_LOGIN --password-stdin registry.heroku.com

          # build & push
          heroku container:push web --app $HEROKU_APP_NAME

          # release
          heroku container:release web --app $HEROKU_APP_NAME
      if: branch =~ /^(master|travis).*/
