version: '3.4'

networks:
  selenoid-test:
    external:
      name: selenoid-test # This assumes network is already created
  # mynetwork:
  #   driver: bridge


services:
  web:
    build: .
    volumes:
      - .:/usr/src/
    depends_on:
      - selenoid
      - selenoid-ui
    environment:
      DJANGO_TEST_PROCESSES: 24
    entrypoint: ["./bin/test.sh"]
    command: python ./manage.py test functional_tests --parallel
    networks:
      selenoid-test: null

  selenoid:
    image: aerokube/selenoid:latest-release
    volumes:
      - "$PWD:/etc/selenoid" # assumed current dir contains browsers.json
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD:/opt/selenoid/video"
      - "$PWD:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "selenoid-test", "-session-attempt-timeout", "30s", "-retry-count", "3", "-limit", "24"]
    ports:
      - "4444:4444"
    networks:
      selenoid-test: null

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    depends_on:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
    networks:
      selenoid-test: null
